### ISSUE TITLE
Refactor package-releases-job to make a Producer

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/package-releases-job#446]
**To-Do**
- [ ] Create a new message class `PackageReleasedMessage` in thoth-messaging
- [ ] Refactor package-release-job to become producer of Kafka Messages
- [ ] Remove not needed metrics

**Comment by bissenbay** [comment]
@fridex Do you want to change [cli](https://github.com/thoth-station/package-releases-job/blob/master/app.py#L271) to something like [main](https://github.com/thoth-station/graph-refresh-job/blob/master/producer.py#L69) like in `graph-refresh-job`?
Options:
1. We change `cli` to `main`.
2. We have both, so `package-release-job` can be run from the command line.

**Comment by fridex** [comment]
> @fridex Do you want to change [cli](https://github.com/thoth-station/package-releases-job/blob/master/app.py#L271) to something like [main](https://github.com/thoth-station/graph-refresh-job/blob/master/producer.py#L69) like in `graph-refresh-job`?
> Options:
> 
> 1. We change `cli` to `main`.
> 2. We have both, so `package-release-job` can be run from the command line.

As discussed on the call, we can keep the `cli` functionality as written.
